# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7306f6554bc3b68f6a7950202c7bdf5c472c9667af9163270c6c5645d1502c9d68d647bb3d85f6bed43e44bb3c4e840ca65d7502eeac1232317214b990133953

test:
  secret_key_base: f3c71a19ca128436e24dc8204f9966bf22e3513d823647d50bfc89575c464a4afa0b145eb3ff8662dbdb624b8cf45d09594bfe9f016c54d644e5038bebbd6328

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
